server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
  profiles:
    active: native
  application:
    name: CONFIG-SERVER
management:
  endpoints:
    web:
      exposure:
        include: "*"

board:
  width: 30
  height: 30
  window:
    size: 5
    testing:
      size: 3




